ARRAY OPERATIONS

ARITHMETIC OPERATIONS

In [24]:
import numpy as np

In [25]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [26]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [27]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [28]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [29]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [30]:
a1//a2

array([0, 0, 0, 0, 0])

In [31]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

BROADCASTING

In [32]:
l = [10,20,30,40]
arr = np.array(l)

In [33]:
for i in l:
    print(i + 10)

20
30
40
50


In [34]:
arr+10

array([20, 30, 40, 50])

In [35]:
arr2 = np.arange(1, 26).reshape(5, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

DEEP AND SHALLOW COPY

In [37]:
a = np.arange(1, 21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [38]:
slice = a[:5]
slice = slice * 10
print(slice)

[10 20 30 40 50]


In [39]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
a[4:6] *10

array([50, 60])

In [41]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
a
b=a.copy()

In [43]:
b[0] = 99

In [44]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

MATRIX OPS

In [46]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [47]:
print(A)

[[1 2]
 [3 4]]


In [48]:
print(B)

[[5 6]
 [7 8]]


In [49]:
A @ B

array([[19, 22],
       [43, 50]])

In [50]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [51]:
A.T

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION

STACKING ARRAY

In [55]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [56]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [58]:
np.column_stack(((a,b)))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

SPLITTING ARRAY

In [59]:
c = np.arange(16).reshape(4, 4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [60]:
result = np.hsplit(c, 4)
print(result)

[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [61]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [62]:
for i in a:
    print(i)

[1 2]
[3 4]
