In [51]:
import numpy as np

BASIC ARRAY CREATION

In [52]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [53]:
a = [1,2,3,4,"hello"]
a

[1, 2, 3, 4, 'hello']

In [54]:
np.array(a)

array(['1', '2', '3', '4', 'hello'], dtype='<U11')

In [55]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr = np.arange(1, 11, 2)
arr


array([1, 3, 5, 7, 9])

In [57]:
arr = np.zeros((4, 8))
arr


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
np.ones((6, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [59]:
arr = np.linspace(0, 1, 100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

RANDOM GENERATION FUNCTION

In [60]:
np.random.rand(10)

array([0.21939269, 0.01770202, 0.21317659, 0.2825872 , 0.80301269,
       0.31589792, 0.06583347, 0.21351905, 0.78457877, 0.68476165])

In [61]:
np.random.randn(10)

array([-1.24214735,  0.62599308, -0.40302168, -1.09996884, -1.89810782,
        0.94263452, -0.80395548, -0.77657903, -0.06082258, -0.0600835 ])

In [62]:
np.random.randint(10,20,6)

array([18, 10, 16, 13, 13, 16])

ARRAY ATTRIBUTE

In [63]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [64]:
arr.shape


(3, 3)

In [65]:
arr.size


9

In [66]:
arr.dtype


dtype('int32')

ARRAY METHODS

In [67]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr.min()

1

In [69]:
arr.max()

9

In [70]:
arr.sum()

45

In [71]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [72]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [73]:
arr.mean()

5.0

In [74]:
arr.std()

2.581988897471611

In [75]:
arr.argmax()

8

In [76]:
arr.argmin()

0

RESHAPING AND RESIZING

In [77]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [78]:
arr=arr.reshape(6,5)

In [79]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

ARRAY INDEXING AND SLICING OF VECTORS

In [80]:
import numpy as np

In [81]:
arr=np.arange(11,21)

In [82]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [83]:
arr[9]

20

In [84]:
arr[1:4]

array([12, 13, 14])

In [85]:
arr[1:5]

array([12, 13, 14, 15])

In [86]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [87]:
arr[3::2]

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [88]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [89]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [90]:
arr[5]

array([26, 27, 28, 29, 30])

In [91]:
arr[0,0]

1

In [92]:
arr[0,4]

5

In [93]:
arr[5,4]

30

In [94]:
arr = np.arange(1, 31).reshape(6, 5)

In [96]:
slice=arr[0:2, 1]
slice

array([2, 7])

In [97]:
slice=arr[3:, 3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [98]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

BOOLIEN INDEXING

In [101]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [102]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [103]:
arr = arr[bool_index]

In [104]:
arr

array([12, 14, 16, 18, 20])